esp8266:
  board: esp01_1m

esphome:
  friendly_name: Fancy Pancy Sensors
  name_add_mac_suffix: true
  name: fancypancy
  comment: "Test voor het installeren van een nieuw device"
  project:
    name: "lschelvis.fancy"
    version: "1.2.0"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dashboard_import:
  package_import_url: github://leejoow/esptest/fancypancy.yaml@main
  import_full_config: true

wifi:
  ap:
    password: "sharingwifi"

captive_portal:
    
switch:
  - platform: gpio
    pin: GPIO16
    name: "Testknopje"
    id: testknop

binary_sensor:
  - platform: gpio
    pin: GPIO15
    name: "Factory Reset"
    device_class: window
    filters:
      - delayed_on_off: 10ms
    on_press:
      - button.press: reset_button

button:
  - platform: factory_reset
    id: reset_button
    name: Restart with Factory Default Settings

